### ISSUE TITLE
Can't login with newly created user 

### ISSUE THREAD

**Issue by nunocgoncalves** [CorefluxCommunity/coreflux-central#3]
### Describe the bug 🐞

  I am not able to login and get a "bad username or password" message

![image](https://github.com/CorefluxCommunity/Coreflux-central/assets/64640406/8912014c-dd3d-4743-9960-1c2553d37f9c)

### To Reproduce 🔄

1. Created user with the ``-addUser <username> <password>`` command published to the ``$SYS/Coreflux/Command/`` topic.
2. Used an autogenerated password with alphanumeric and special characters. Example: ``NkZ?\u003e=P?``
3. Got success message.
4. Attempted to login with new user and password and got "bad username or password" message.

### Expected behavior ✅

The user credentials allow me to login (with MQTT Explorer)

### Environment 🌐

Ubuntu 22.04 LTS (Jammy Jellyfish)

### Terms of Service

- [X] I agree

**Comment by HugoAVaz** [comment]
I was able to mimic in Linux, but solve it by running sudo ./CorefluxCentral.
![image](https://github.com/CorefluxCommunity/Coreflux-central/assets/60146011/1d59d58c-56d9-4fbb-b9bd-1d64a88e505d)

connecting 
![image](https://github.com/CorefluxCommunity/Coreflux-central/assets/60146011/4ec9e3c6-74b5-4ddc-93a3-65873bfff2d4)

done
![image](https://github.com/CorefluxCommunity/Coreflux-central/assets/60146011/5b912b79-1ea3-4230-96ec-b90fb2fded16)

If we lack the necessary permissions to write to the files or folders under Linux or within a Docker volume, the broker process fails to write within the user database system and logs a message.. 

I should pass this to the documentation and improve the feedback.
